version: '3'

services:

  app:
    container_name: postemailer
    restart: unless-stopped
    build: ./app
    volumes:
      - "$PWD/.env:/app/.env"
    environment:
      - NODE_ENV=production

  nginx:
    container_name: nginx
    restart: unless-stopped
    build: ./nginx
    ports:
      - "8080:80"