version: '3'

services:

  app:
    container_name: postemailer
    restart: unless-stopped
    build: ./app
    volumes: ['./app:/app']
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  nginx:
    container_name: nginx
    restart: unless-stopped
    build: ./nginx
    expose:
      - "80"
    ports:
      - "80:80"