kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: smtpie
  name: smtpie-db
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/smtpie/volume-db"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: smtpie
  name: smtpie-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
