apiVersion: v1
kind: Service
metadata:
  labels:
    app: smtpie
  name: smtpie
  namespace: smtpie
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: smtpie
